routes/web.php
<?php
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login')->name('login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// third-party Twitter Auth
Route::get('twitter/auth', 'Twitter\authController@auth')->name('twitter-auth');
Route::get('twitter/callback', 'Twitter\authController@callback')->name('twitter-callback');

Route::redirect('/', '/dashboard');

Route::get('/dashboard', 'MainController@index')->middleware('auth')->name('dashboard');
Route::get('/settings', 'MainController@settings')->middleware('auth')->name('settings');
Route::post('/settings', 'MainController@updateSettings')->middleware('auth')->name('updateSettings');

// Skripsi Routes
Route::middleware(['auth'])->namespace('Skripsi')->name('skripsi.')->group( function() {
    Route::prefix('crawling')->name('crawling.')->group( function(){
        Route::get('/', 'CrawlingController@index')->name('index');
        Route::post('/', 'CrawlingController@crawling')->name('crawling');
    });

    Route::prefix('flagging')->name('flagging.')->group( function(){
        Route::get('/', 'FlaggingController@index')->name('index');
        Route::get('/training', 'FlaggingController@training')->name('training');
        Route::get('/count', 'FlaggingController@count')->name('count');
        Route::post('/', 'FlaggingController@flagging')->name('flagging');
        Route::get('/destroy', 'FlaggingController@destroy')->name('destroy');

    });

    Route::prefix('preprocessing')->name('preprocessing.')->group( function(){
        Route::get('/', 'PreprocessingController@index')->name('index');
    });

    Route::get('/a-dump', 'DumpController@index');
    Route::get('/b-dump', 'DumpController@naiveBayes');
    Route::get('/c-dump', 'DumpController@testing');
});
// Skripsi Routes

resources/views/back/partials/head.blade.php
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=Edge">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<meta name="keywords" content="HTML,CSS,XML,JavaScript">
<meta name="author" content="{{ env('APP_CREATOR', 'CODEBREEDER') }}">
<title>{{ config('app.name', 'AdminBSB - Boilerplate') }}</title>
<!-- <link rel="icon" href="{{asset('vendor/AdminBSB')}}/favicon.ico" type="image/x-icon"> -->
<link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">
<link href="{{asset('vendor/AdminBSB')}}/plugins/bootstrap/css/bootstrap.css" rel="stylesheet">
<link href="{{asset('vendor/AdminBSB')}}/plugins/node-waves/waves.css" rel="stylesheet" />
<link href="{{asset('vendor/AdminBSB')}}/plugins/animate-css/animate.css" rel="stylesheet" />
<link href="{{asset('vendor/AdminBSB')}}/plugins/morrisjs/morris.css" rel="stylesheet" />
<link href="{{asset('vendor/AdminBSB')}}/css/style.css" rel="stylesheet">
<link href="{{asset('vendor/AdminBSB')}}/css/themes/all-themes.css" rel="stylesheet" />

<link href="{{asset('vendor/AdminBSB')}}/plugins/bootstrap-select/css/bootstrap-select.css" rel="stylesheet" />
<link href="{{asset('vendor/AdminBSB')}}/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css" rel="stylesheet">
@yield('css')

resources/views/back/partials/left-sidebar.blade.php
<aside id="leftsidebar" class="sidebar">
    <div class="user-info">
        <div class="row">
            <a href="{{route('settings')}}">
                <div class="image col-xs-2">
                    @if(empty($loguser->avatar))
                        <img src="{{asset('vendor/AdminBSB')}}/images/user.png" width="48" height="48" alt="User" />
                    @else
                        <img src="{{$loguser->avatar}}" width="48" height="48" alt="User" />
                    @endif
                </div>
            </a>
            <div class="info-container col-xs-7">
                <div class="name" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <b>{{$loguser->name}}</b></div>
                <div class="email">{{$loguser->email}}</div>
            </div>
            <div class="info-container col-xs-2" style="top:20px;">
                <a href="{{ route('logout') }}" onclick="event.preventDefault();
                    document.getElementById('logout-form').submit();" style="color:white;" title="Keluar">
                    <i class="material-icons">exit_to_app</i>
                </a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            </div>
        </div>
    </div>
    
    <div class="menu">
        <ul class="list">
            <li class="header">MAIN NAVIGATION</li>
            <li class="{{(Request::segment(1) == 'dashboard')?'active':''}}">
                <a href="{{route('dashboard')}}">
                    <i class="material-icons">home</i>
                    <span>Home</span>
                </a>
            </li>

{{-- Tools Naive-Bayes --}}
            <li class="header">NAIVE-BAYES</li>
            <li class="{{(Request::segment(1) == 'crawling')?'active':''}}">
                <a href="{{route('skripsi.crawling.index')}}">
                    <i class="material-icons">search</i>
                    <span>Crawl Tweets</span>
                </a>
            </li>
            <li class="{{(Request::segment(1) == 'flagging')?'active':''}}">
                <a href="{{route('skripsi.flagging.index')}}">
                    <i class="material-icons">flag</i>
                    <span>Training</span>
                </a>
            </li>
            <li class="{{(Request::segment(1) == 'preprocessing')?'active':''}}">
                <a href="{{route('skripsi.preprocessing.index')}}">
                    <i class="material-icons">settings</i>
                    <span>Preprocessing</span>
                </a>
            </li>
{{-- Tools Naive-Bayes --}}

        </ul>
    </div>
    
    <div class="legal">
        <div class="copyright">
            &copy; {{date('Y')}} <a href="javascript:void(0);">{{ config('app.name', 'AdminBSB - Boilerplate') }}</a>.
        </div>
        <div class="version">
            <b>Version: </b> {{ env('APP_VERSION', 'Developing') }}
        </div>
    </div>
</aside>

resources/views/back/partials/loader.blade.php
<div class="page-loader-wrapper">
    <div class="loader">
        <div class="preloader">
            <div class="spinner-layer pl-blue">
                <div class="circle-clipper left">
                    <div class="circle"></div>
                </div>
                <div class="circle-clipper right">
                    <div class="circle"></div>
                </div>
            </div>
        </div>
        <p>Please wait...</p>
    </div>
</div>

resources/views/back/partials/navbar.blade.php
<nav class="navbar">
    <div class="container-fluid">
        <div class="navbar-header">
            <a href="javascript:void(0);" class="bars"></a>
            <a class="navbar-brand" href="">{{ config('app.name', 'AdminBSB - Boilerplate') }}</a>
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapse">
            <ul class="nav navbar-nav navbar-right">

                <li class="dropdown">
                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button">
                        <i class="material-icons">notifications</i>
                        <span class="label-count">1</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">NOTIFICATIONS</li>
                        <li class="body">
                            <ul class="menu">
                                <li>
                                    <a href="javascript:void(0);">
                                        <div class="icon-circle bg-light-green">
                                            <i class="material-icons">person_add</i>
                                        </div>
                                        <div class="menu-info">
                                            <h4>12 new members joined</h4>
                                            <p>
                                                <i class="material-icons">access_time</i> 14 mins ago
                                            </p>
                                        </div>
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

resources/views/back/partials/script.blade.php
<script src="{{asset('vendor/AdminBSB')}}/plugins/jquery/jquery.min.js"></script>
<script src="{{asset('vendor/AdminBSB')}}/plugins/bootstrap/js/bootstrap.js"></script>
<script src="{{asset('vendor/AdminBSB')}}/plugins/bootstrap-select/js/bootstrap-select.js"></script>
<script src="{{asset('vendor/AdminBSB')}}/plugins/jquery-slimscroll/jquery.slimscroll.js"></script>
<script src="{{asset('vendor/AdminBSB')}}/plugins/node-waves/waves.js"></script>
<script src="{{asset('vendor/AdminBSB')}}/plugins/jquery-countto/jquery.countTo.js"></script>
<script src="{{asset('vendor/AdminBSB')}}/plugins/raphael/raphael.min.js"></script>
<script src="{{asset('vendor/AdminBSB')}}/plugins/morrisjs/morris.js"></script>
<script src="{{asset('vendor/AdminBSB')}}/plugins/chartjs/Chart.bundle.js"></script>
<script src="{{asset('vendor/AdminBSB')}}/plugins/flot-charts/jquery.flot.js"></script>
<script src="{{asset('vendor/AdminBSB')}}/plugins/flot-charts/jquery.flot.resize.js"></script>
<script src="{{asset('vendor/AdminBSB')}}/plugins/flot-charts/jquery.flot.pie.js"></script>
<script src="{{asset('vendor/AdminBSB')}}/plugins/flot-charts/jquery.flot.categories.js"></script>
<script src="{{asset('vendor/AdminBSB')}}/plugins/flot-charts/jquery.flot.time.js"></script>
<script src="{{asset('vendor/AdminBSB')}}/plugins/jquery-sparkline/jquery.sparkline.js"></script>
<script src="{{asset('vendor/AdminBSB')}}/js/admin.js"></script>
<script src="{{asset('vendor/AdminBSB')}}/js/pages/index.js"></script>
<script src="{{asset('vendor/AdminBSB')}}/js/demo.js"></script>

<script src="{{asset('vendor/AdminBSB')}}/plugins/jquery-datatable/jquery.dataTables.js"></script>
<script src="{{asset('vendor/AdminBSB')}}/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js"></script>
<script src="{{asset('vendor/AdminBSB')}}/js/pages/tables/jquery-datatable.js"></script>

<script src="https://cdn.ckeditor.com/4.12.1/full/ckeditor.js"></script>

<script>
    CKEDITOR.replace('ckeditor');
    $('.dataTable').DataTable({
        "pageLength": 25
    });
</script>

@yield('script')